### ISSUE TITLE
Q - AS5600 magnetic encoder 

### ISSUE THREAD

**Issue by DrumClock** [Aus3D/MagneticEncoder#3]
Hi, is it possible to use this magnetic encoder for Marlin FW?

![AS5600](https://user-images.githubusercontent.com/64655979/103539590-a7ac1400-4e98-11eb-8d4d-9465bf3420b1.PNG)

Thanks :)

**Comment by Fusseldieb** [comment]
Same question

**Comment by Fusseldieb** [comment]
Why did you close the issue @DrumClock ?

**Comment by DrumClock** [comment]
Nobody was interested in over a year, so why leave it open ... It doesn't make sense.

**Comment by jwdriessen** [comment]
I would love to know how to set this up with marlin 2.0.
I have set up this encoder and try to test it with moving the X motor and holding the axis firmly
I would expect that the encoder makes up for the missed steps but that is not happening.
Is there anyone out there who has this working with a NEMA 17 motor?
Regards JWD

**Comment by theohenrichs** [comment]
Hi jwdriessen

Reading https://github.com/MarlinFirmware/Marlin/issues/21138 it seems that Marlin doesn't support this type of position-thing at all anymore .....

Quote from DrumClock @ 21 Feb 2021

> That's probably why Aus3D ended up with the production of its module, and the function in Marlin is just a remnant that is no longer used.

Endquote ...

**Comment by chrissbarr** [comment]
Hi all,

Sorry that there's been no proper reply here before.

The AS5600 is a fairly different type of encoder to the one that was used in these modules. I did not write any Marlin firmware feature to support encoders like the AS5600. I had planned to, but do not believe it ever made it to a working state. Others may have done so, but I am unsure.

Additionally, the encoder modules in this repo (and supported by the Marlin code I wrote) were implemented with an onboard AVR microcontroller that managed each encoder IC. The AVR firmware implemented a slave I2C interface that Marlin communicated with (e.g., the Marlin FW never directly touched the encoder IC's I2C interface). This was done because each encoder needed to be read at a higher rate than was practical from the central Marlin FW (it also allowed the use of different I2C addresses, and the implementation of a checksum to add some noise tolerance to the long I2C bus). 

So, if you want to directly talk to the AS5600 using I2C from Marlin, you should ignore the work I did previously.

The error correction behaviour itself that I added to Marlin could definitely be adapted to the AS5600 (or any other comparable encoder). 

**So, in short, I would say**: there is no reason the AS5600 couldn't be used in Marlin, but the I2C-related code I wrote will not be helpful, and I don't know if anyone else has written something suitable. There may be issues relating to the required update-rate, noise tolerance, and I2C address selection. If the I2C interface can be implemented, the error-correction code I added can likely be adapted. However I don't think there is any simple configuration option to enable the desired behaviour - someone would need to implement it.

Aus3D stopped producing these encoder modules for two reasons:

1. The total cost to upgrade a printer with the linear encoders was quite high (around 60 USD per axis, so say 180 USD per printer) - there did not seem to be a lot of demand at this price point.
2. The encoder IC we were using (NSE5310 or AS5311) went out of stock for over a year and we were unable to produce any more modules.

I hope that sheds some clarity on this topic. Sorry that I'm not adding any positive news here. Happy to answer any further questions though.
